apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: dev
  labels:
    app: myapp
    component: tempo
spec:
  selector:
    app: tempo
  ports:
    - name: tempo-http
      protocol: TCP
      port: 3200
      targetPort: 3200
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
  type: ClusterIP
