apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: dev
  labels:
    app: myapp
    component: tempo
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200
  type: ClusterIP
