apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: dev
  labels:
    app: myapp
    component: tempo
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      
    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_http:
              endpoint: 0.0.0.0:14268
        zipkin:
          endpoint: 0.0.0.0:9411
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
              
    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1000000
      max_block_duration: 5m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      
    compactor:
      compaction:
        compaction_window: 1h
        max_compaction_objects: 1000000
        block_retention: 1h
        compacted_block_retention: 10m
      ring:
        kvstore:
          store: inmemory
        wait_stability_min_duration: 0s
        wait_stability_max_duration: 0s
        
    storage:
      trace:
        backend: local
        wal:
          path: /tmp/tempo/wal
        local:
          path: /tmp/tempo/blocks
          
    querier:
      max_concurrent_queries: 5
      
    query_frontend:
      search:
        duration_slo: 5s
        throughput_bytes_slo: 1e+09
      trace_by_id:
        duration_slo: 5s
        
    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: dev
      storage:
        path: /tmp/tempo/generator/wal
        remote_write:
          - url: http://mimir:8080/api/v1/push
            send_exemplars: true
