apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: dev
  labels:
    app: myapp
    component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'fastapi-backend'
        static_configs:
          - targets: ['backend:8000']
        metrics_path: '/api/metrics'
        scrape_interval: 10s

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

    remote_write:
      - url: http://mimir:8080/api/v1/push
        name: mimir
