apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
  labels:
    app: myapp
    component: backend
data:
  # Non-sensitive configuration
  POSTGRES_PORT: "5432"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  # Application settings
  LOG_LEVEL: "INFO"
  APP_ENV: "development"
