apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
  labels:
    app: myapp
    component: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
