apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: myapp
    component: redis
spec:
  capacity:
    storage: 1Gi              # Smaller than postgres - redis needs less space
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath: # For minikube
    path: /data/redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: dev
  labels:
    app: myapp
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: redis-pv
