apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dev
  labels:
    app: myapp
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: infra-frontend:latest
        imagePullPolicy: Never  # For local minikube images
        ports:
        - containerPort: 80  # nginx serves on port 80
        # Frontend is static files, no environment variables needed
        # All API calls go through the main nginx reverse proxy
        resources:
          requests:
            memory: "64Mi"   # Frontend needs less memory (static files)
            cpu: "50m"       # Frontend needs less CPU
          limits:
            memory: "128Mi"
            cpu: "100m"
        # Health checks for nginx
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
