apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: dev
  labels:
    app: myapp
    component: mimir
spec:
  selector:
    app: mimir
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
