apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: dev
  labels:
    app: myapp
    component: loki
data:
  # Loki configuration via environment variables
  LOKI_AUTH_ENABLED: "false"
  LOKI_HTTP_LISTEN_PORT: "3100"
  LOKI_LOG_LEVEL: "info"
  LOKI_STORAGE_PATH: "/loki"
  LOKI_CHUNKS_DIR: "/loki/chunks"
  LOKI_RULES_DIR: "/loki/rules"
