apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: dev
  labels:
    app: myapp
    component: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: infra-loki:latest
        imagePullPolicy: Never  # For local minikube images
        ports:
        - containerPort: 3100
          name: loki-http
        envFrom:
        - configMapRef:
            name: loki-config
        volumeMounts:
        - name: loki-data
          mountPath: /loki
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: loki-data
        emptyDir: {}
