{
 "title": "Mimir dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "x >= 400 status code",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "  {span.http.status_code >= 400}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces by name",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"fastapi-backend\"} | by(name)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Latest Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 17 },
   "targets": [
    { "limit": 20, "metricsQueryType": "range", "query": "{}", "tableType": "traces" }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (endpoint) (http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}