apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: dev
  labels:
    app: myapp
    component: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  clusterIP: None # Headless service for StatefulSet
