apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: dev
  labels:
    app: myapp
    component: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: grafana-web
  type: NodePort
