name: check_python

on:
  pull_request:
  workflow_run:
    workflows: ["secrets_check"]
    types:
      - completed

jobs:
  lint_and_test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container:
      image: python:alpine3.21
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apk add --no-cache gcc musl-dev libffi-dev
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r backend/requirements.txt

      - name: Run Ruff linter
        run: ruff check . --output-format=github

      - name: Run Pytest
        run: pytest --cov --cov-report=term-missing

      - name: Run Python Security check
        run: bandit -r backend/

      - name: Run mypy Static analisys
        run: mypy backend/ --explicit-package-bases
