name: check_python

on:
  pull_request

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    container:
      image: python:alpine3.21
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apk add --no-cache gcc musl-dev libffi-dev
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r backend/requirements.txt

      - name: Run Ruff
        run: ruff check . --output-format=github

      - name: Run Pytest
        run: pytest --cov=backend.core.db --cov-report=term-missing
