name: complete_workflow

on:
  pull_request:

jobs:
  secrets_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
            command: "detect --source . --verbose"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check_python:
    runs-on: ubuntu-latest
    needs: secrets_check
    container:
      image: python:alpine3.21
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apk add --no-cache gcc musl-dev libffi-dev
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r backend/requirements.txt

      - name: Run Ruff linter
        run: ruff check . --output-format=github

      - name: Run Pytest
        run: pytest --cov --cov-report=term-missing

      - name: Run Python Security check
        run: bandit -r backend/

      - name: Run mypy Static analisys
        run: mypy backend/ --explicit-package-bases
